name: Deploy Documentation

on:
  push:
    branches:
      - main
      - 'v*'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Get all version branches
        id: get-versions
        run: |
          echo "Listing all remote branches:"
          git branch -r
          
          echo "Detecting version branches:"
          git branch -r | grep 'origin/v' || echo "No version branches found"
          
          echo "Setting VERSIONS environment variable:"
          echo "VERSIONS<<EOF" >> $GITHUB_ENV
          git branch -r | grep 'origin/v' | sed 's/origin\///' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          echo "Current branch:"
          git branch --show-current
          echo "::set-output name=current_branch::$(git branch --show-current)"

      - name: Build main branch (latest)
        run: |
          mkdir -p _site/latest
          # Create a temporary config file with updated baseurl
          echo "Creating temporary config file for latest version..."
          cp "./_config.yml" "./temp_config_latest.yml"
          echo "baseurl: \"/documentation/latest\"" >> "./temp_config_latest.yml"
          
          # Build with the temporary config
          bundle exec jekyll build --config "./temp_config_latest.yml" -d _site/latest
          
          # Note: We're not copying to root as per requirement

      - name: Build version branches
        run: |
          for branch in $VERSIONS; do
            echo "Building documentation for $branch"
            git checkout $branch
            mkdir -p _site/$branch
            
            # Create a temporary config file with updated baseurl
            echo "Creating temporary config file for $branch version..."
            cp "./_config.yml" "./temp_config_version_$branch.yml"
            echo "baseurl: \"/documentation/$branch\"" >> "./temp_config_version_$branch.yml"
            
            # Build with the temporary config
            bundle exec jekyll build --config "./temp_config_version_$branch.yml" -d _site/$branch
            
            # Create a .nojekyll file to prevent GitHub Pages from processing the site
            touch _site/$branch/.nojekyll
          done
          
          # Create a .nojekyll file in the root to prevent GitHub Pages from processing the site
          touch _site/.nojekyll
          
          # Create a redirect from root to /latest
          echo '<meta http-equiv="refresh" content="0; url=latest/">' > _site/index.html
          
          git checkout ${{ steps.get-versions.outputs.current_branch }}

      - name: Generate version selector data
        run: |
          echo "Creating version selector data"
          echo "Available versions: latest $VERSIONS"
          
          # Create versions.json with proper JSON format
          echo '{"versions":["latest"' > _site/versions.json
          for branch in $VERSIONS; do
            echo ',"'$branch'"' >> _site/versions.json
          done
          echo ']}' >> _site/versions.json
          
          # Display the content of versions.json
          echo "Content of versions.json:"
          cat _site/versions.json
          
          # Copy versions.json to each version directory for redundancy
          echo "Copying versions.json to version directories"
          cp _site/versions.json _site/latest/versions.json
          echo "Copied to latest directory"
          
          for branch in $VERSIONS; do
            if [ -d "_site/$branch" ]; then
              cp _site/versions.json _site/$branch/versions.json
              echo "Copied to $branch directory"
            else
              echo "Warning: Directory _site/$branch does not exist"
            fi
          done
          
          # Create a .nojekyll file in each version directory
          echo "Creating .nojekyll files in each version directory"
          touch _site/.nojekyll
          touch _site/latest/.nojekyll
          for branch in $VERSIONS; do
            if [ -d "_site/$branch" ]; then
              touch _site/$branch/.nojekyll
              echo "Created .nojekyll in $branch directory"
            fi
          done

      - name: Clean up temporary config files
        run: |
          echo "Cleaning up temporary config files..."
          rm -f ./temp_config_*.yml
          
      - name: Ensure version selector files are in each version
        run: |
          # Copy version selector files to each version directory
          echo "Copying version selector files to each version directory..."
          
          # First, ensure latest directory exists and copy files there
          if [ -d "_site/latest" ]; then
            mkdir -p _site/latest/assets/js
            mkdir -p _site/latest/assets/css
            cp assets/js/version-selector.js _site/latest/assets/js/
            cp assets/css/version-selector.css _site/latest/assets/css/
            echo "Copied files to _site/latest"
          fi
          
          # Then handle version directories
          for branch in $VERSIONS; do
            if [ -d "_site/$branch" ]; then
              mkdir -p _site/$branch/assets/js
              mkdir -p _site/$branch/assets/css
              cp assets/js/version-selector.js _site/$branch/assets/js/
              cp assets/css/version-selector.css _site/$branch/assets/css/
              echo "Copied files to _site/$branch"
            fi
          done
          
      - name: List directory structure before upload
        run: |
          echo "Directory structure before upload:"
          find _site -type d | sort
          
          echo "Content of versions.json files:"
          find _site -name "versions.json" -exec echo {} \; -exec cat {} \;
          
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4